# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [15]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """
    print("a_slice_prev: ", a_slice_prev)
    print("W: ", W)
    print("b: ", b)
    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''

'\n\nnp.random.seed(1)\n#定義一個 axaxd 的 feature map\na_slice_prev = \nW = \nb = np.random.randn(1, 1, 1)\n\n#取得計算後,卷積矩陣的值\nZ = conv_single_step(a_slice_prev, W, b)\nprint("Z =", Z)\n'

In [18]:
#np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(32,32,3)
W = np.random.randn(32,32,3)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

a_slice_prev:  [[[ 1.81745728 -1.03440265  0.36405134]
  [-1.07943569  1.93102718  0.75083074]
  [-2.10190845  0.46896507  0.02542339]
  ...
  [-1.41277786  0.40437433 -0.02414115]
  [ 0.92012611 -0.62585407  1.41467206]
  [ 0.5237272  -0.51926476  0.99439043]]

 [[ 0.30342218 -3.22261392  1.01410955]
  [ 0.10791995 -0.27631945 -1.05562128]
  [ 0.39780231  0.5747821  -1.50822511]
  ...
  [ 1.3628747   0.8035312  -0.02113656]
  [ 2.47795051  0.70482992  1.97982351]
  [ 0.48390564  0.52539068  0.81276247]]

 [[ 0.96991312 -0.55748874  0.02911671]
  [ 1.07888391 -1.15594233  0.06733799]
  [-0.44765519 -0.39138622 -0.03192311]
  ...
  [ 0.47677903  0.08396882  0.33579182]
  [-1.95662106 -0.88622697 -1.60311711]
  [-0.80858115 -0.11742265  0.49635741]]

 ...

 [[-0.97745696  0.56481502 -0.37521145]
  [ 0.54855455 -0.79297974 -0.25219259]
  [-0.26961355  1.24802407 -1.60534869]
  ...
  [ 0.21757841 -0.29397661 -0.24379328]
  [ 0.15171071 -2.38722682  0.88781663]
  [-0.03120522  0.5713947   1

In [14]:
#np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(16,16,1)
W = np.random.randn(16,16,1)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = -24.01443295296144


In [12]:
#np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(2,2,1)
W = np.random.randn(2,2,1)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = 0.18076477016553294
